name: Generate a CycloneDX SBOM with composer and uploads it
description: |
  Utilizes cyclonedx-php-composer to generate a SBOM. This SBOM will then be archived and uploaded to Github.

  Prerequisite: `composer require --dev cyclonedx/cyclonedx-php-composer`

inputs:
  publish:
    description: "Publish SBOM to Github"
    required: false
    default: 'false'
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      shell: bash
      id: context
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        echo "bom-path=$working_directory/build/reports/bom.json" >> $GITHUB_OUTPUT

    - name: Generate BOM
      shell: bash
      run: |
        mkdir -p build/reports
        composer make-bom --no-interaction --output-format=JSON --output-file=${{ steps.context.outputs.bom-path }}

    - name: Archive BOM
      uses: actions/upload-artifact@v4
      if: "!cancelled()"
      with:
        name: bom.json
        retention-days: ${{ inputs.report-retention-days }}
        path: ${{ steps.context.outputs.bom-path }}

    - name: Upload BOM
      uses: evryfs/sbom-dependency-submission-action@v0.0.14
      with:
        sbom-files: ${{ steps.context.outputs.bom-path }}
